drop table if exists member cascade;

create table member (
    id bigint generated by default as identity ,
    name varchar(255),
    primary key
)

/* id는 bigint 형  뒤에 붙은거는  id가 null 값으로 인서트 되었을때 db에서 자동으로 값을 넣어줌*/